CREATE DATABASE cookie default CHARACTER SET UTF8;
use cookie;
CREATE TABLE cookietable(
    numbers INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cookie VARCHAR(300) NOT NULL,
    currentdate DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;